[2021-11-11 13:01:21,070] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: dag-2.model_B manual__2021-11-11T13:01:19.250340+00:00 [queued]>
[2021-11-11 13:01:21,097] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: dag-2.model_B manual__2021-11-11T13:01:19.250340+00:00 [queued]>
[2021-11-11 13:01:21,098] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-11 13:01:21,099] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-11 13:01:21,102] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-11 13:01:21,128] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): model_B> on 2021-11-11 13:01:19.250340+00:00
[2021-11-11 13:01:21,141] {standard_task_runner.py:52} INFO - Started process 4199 to run task
[2021-11-11 13:01:21,152] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag-2', 'model_B', 'manual__2021-11-11T13:01:19.250340+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/DAG-2.py', '--cfg-path', '/tmp/tmp_3lg9dcl', '--error-file', '/tmp/tmp1ac1dt6h']
[2021-11-11 13:01:21,153] {standard_task_runner.py:77} INFO - Job 17: Subtask model_B
[2021-11-11 13:01:21,266] {logging_mixin.py:109} INFO - Running <TaskInstance: dag-2.model_B manual__2021-11-11T13:01:19.250340+00:00 [running]> on host 150ca14c9dd9
[2021-11-11 13:01:21,370] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag-2
AIRFLOW_CTX_TASK_ID=model_B
AIRFLOW_CTX_EXECUTION_DATE=2021-11-11T13:01:19.250340+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-11T13:01:19.250340+00:00
[2021-11-11 13:01:21,377] {python.py:152} INFO - Done. Returned value was: 9
[2021-11-11 13:01:21,445] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=dag-2, task_id=model_B, execution_date=20211111T130119, start_date=20211111T130121, end_date=20211111T130121
[2021-11-11 13:01:21,489] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-11 13:01:21,568] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
