[2021-11-11 13:01:21,026] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: dag-2.model_C manual__2021-11-11T13:01:19.250340+00:00 [queued]>
[2021-11-11 13:01:21,064] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: dag-2.model_C manual__2021-11-11T13:01:19.250340+00:00 [queued]>
[2021-11-11 13:01:21,065] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-11 13:01:21,066] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-11 13:01:21,068] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-11 13:01:21,101] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): model_C> on 2021-11-11 13:01:19.250340+00:00
[2021-11-11 13:01:21,113] {standard_task_runner.py:52} INFO - Started process 4198 to run task
[2021-11-11 13:01:21,130] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag-2', 'model_C', 'manual__2021-11-11T13:01:19.250340+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/DAG-2.py', '--cfg-path', '/tmp/tmp8k1wxaae', '--error-file', '/tmp/tmp7jfi6bmu']
[2021-11-11 13:01:21,131] {standard_task_runner.py:77} INFO - Job 16: Subtask model_C
[2021-11-11 13:01:21,239] {logging_mixin.py:109} INFO - Running <TaskInstance: dag-2.model_C manual__2021-11-11T13:01:19.250340+00:00 [running]> on host 150ca14c9dd9
[2021-11-11 13:01:21,374] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag-2
AIRFLOW_CTX_TASK_ID=model_C
AIRFLOW_CTX_EXECUTION_DATE=2021-11-11T13:01:19.250340+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-11T13:01:19.250340+00:00
[2021-11-11 13:01:21,384] {python.py:152} INFO - Done. Returned value was: 9
[2021-11-11 13:01:21,488] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=dag-2, task_id=model_C, execution_date=20211111T130119, start_date=20211111T130121, end_date=20211111T130121
[2021-11-11 13:01:21,543] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-11 13:01:21,644] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
